name: "Nairobi-Streetkids"
description: "The Personal Homepage for Erick Gathege"

url: "http://ric254.github.io"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
